# Generated by Django 3.1 on 2020-09-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=64)),
                ('pet_birth', models.DateField()),
                ('pet_gender', models.CharField(choices=[('Male', 'Samiec'), ('Female', 'Samica'), ('Unknown', 'Nie Wybrano')], default='Unknown', max_length=24)),
                ('pet_weight', models.CharField(choices=[('0', 'Nie Wybrano'), ('1', '1 kg'), ('2', '2 kg'), ('3', '3 kg'), ('4', '4 kg'), ('5', '5 kg'), ('6', '6 kg'), ('7', '7 kg'), ('8', '8 kg'), ('9', '9 kg'), ('10', '10 kg'), ('11', '11 kg'), ('12', '12 kg'), ('13', '13 kg'), ('14', '14 kg'), ('15', '15 kg'), ('16', '16 kg'), ('17', '17 kg'), ('18', '18 kg'), ('19', '19 kg'), ('20', '20 kg'), ('21', '21 kg'), ('22', '22 kg'), ('23', '23 kg'), ('24', '24 kg'), ('25', '25 kg'), ('26', '26 kg'), ('27', '27 kg'), ('28', '28 kg'), ('29', '29 kg'), ('30', '30 kg'), ('31', '31 kg'), ('32', '32 kg'), ('33', '33 kg'), ('34', '34 kg'), ('35', '35 kg'), ('36', '36 kg'), ('37', '37 kg'), ('38', '38 kg'), ('39', '39 kg'), ('40', '40 kg'), ('41', '41 kg'), ('42', '42 kg'), ('43', '43 kg'), ('44', '44 kg'), ('45', '45 kg'), ('46', '46 kg'), ('47', '47 kg'), ('48', '48 kg'), ('49', '49 kg'), ('50', '50 kg'), ('51', '51 kg'), ('52', '52 kg'), ('53', '53 kg'), ('54', '54 kg'), ('55', '55 kg'), ('56', '56 kg'), ('57', '57 kg'), ('58', '58 kg'), ('59', '59 kg'), ('60', '60 kg'), ('61', '61 kg'), ('62', '62 kg'), ('63', '63 kg'), ('64', '64 kg'), ('65', '65 kg'), ('66', '66 kg'), ('67', '67 kg'), ('68', '68 kg'), ('69', '69 kg'), ('70', '70 kg'), ('71', '71 kg'), ('72', '72 kg'), ('73', '73 kg'), ('74', '74 kg'), ('75', '75 kg'), ('76', '76 kg'), ('77', '77 kg'), ('78', '78 kg'), ('79', '79 kg'), ('80', '80 kg'), ('81', '81 kg'), ('82', '82 kg'), ('83', '83 kg'), ('84', '84 kg'), ('85', '85 kg'), ('86', '86 kg'), ('87', '87 kg'), ('88', '88 kg'), ('89', '89 kg'), ('90', '90 kg'), ('91', '91 kg'), ('92', '92 kg'), ('93', '93 kg'), ('94', '94 kg'), ('95', '95 kg'), ('96', '96 kg'), ('97', '97 kg'), ('98', '98 kg'), ('99', '99 kg')], default='0', max_length=24)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('pet_species', models.CharField(choices=[('Dog', 'Pies'), ('Cat', 'Kot'), ('Unknown', 'Nie Wybrano')], default='Unknown', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PetOwner_name', models.CharField(max_length=64)),
                ('PetOwner_birth', models.DateField()),
                ('PetOwner_gender', models.CharField(choices=[('Woman', 'Kobieta'), ('Man', 'Mężczyzna'), ('Unknown', 'Nie Wybrano')], default='Unknown', max_length=11)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('premium_account', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.TextField(max_length=128)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vetname', models.CharField(blank=True, max_length=64, null=True)),
                ('comments', models.CharField(blank=True, max_length=64, null=True)),
                ('visit_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.petowner'),
        ),
    ]
